base_url = "https://virajsazzala.dev"
description = "Viraj Sazzala's personal website"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "base16-ocean-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Viraj"
display_author = false

favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = false

header_nav = [
  { url = "/", name_en = "home" },
  { url = "/about", name_en = "about" },
  { url = "/devlogs", name_en = "devlogs" },
  { url = "/blog", name_en = "blog" },
  { url = "/viraj-resume.pdf", name_en = "resume" }
]